### ISSUE TITLE
Update to new Avalonia.FuncUI NuGet package

### ISSUE THREAD

**Issue by JordanMarr** [SilkyFowl/Avalonia.FuncUI.LiveView#17]
Greetings!

Recently, FuncUI has been officially added to the Avalonia family, which has allowed us to change the NuGet package name from `JaggerJo.Avalonia.FuncUI` to `Avalonia.FuncUI`.

Would it be possible to release a new version of LiveView that works with the latest `Avalonia.FuncUI` package?

**Comment by SilkyFowl** [comment]
@JordanMarr It has been a while since we have heard from you. It is now supported by the new package. Please check if you would like to see it.

**Comment by JordanMarr** [comment]
Awesome! I will give it a try. 🚀

**Comment by SilkyFowl** [comment]
This issue is closed as it has been supported in v0.0.3.

https://github.com/SilkyFowl/Avalonia.FuncUI.LiveView/commit/e2c7270f425df1251e22ca8599731cf2e5020bd6
