### ISSUE TITLE
Error occured when unchecking "Show EvalText"

### ISSUE THREAD

**Issue by ijklam** [SilkyFowl/Avalonia.FuncUI.LiveView#3]
![image](https://user-images.githubusercontent.com/43789618/173692056-17b1dce0-47d3-4f62-9687-1ca4a178c7c8.png)

![image](https://user-images.githubusercontent.com/43789618/173691888-87c56af9-e0a9-435c-8258-72b335467f30.png)

**Comment by SilkyFowl** [comment]
Thanks for the report.
I will look into it.

**Comment by SilkyFowl** [comment]
Sorry, I couldn't replay this error.It may take some time....


https://user-images.githubusercontent.com/16532218/174038350-00fb9cd2-afba-474c-b41b-c197a56584db.mp4

**Comment by SilkyFowl** [comment]
The library has been updated.
Will the new method have the same bugs?

**Comment by ijklam** [comment]
It works fine now. Thanks.
