### ISSUE TITLE
FuncUiAnalyzer server is not active

### ISSUE THREAD

**Issue by JordanMarr** [SilkyFowl/Avalonia.FuncUI.LiveView#7]
_Moved from [Avalonia.FuncUI issues.](https://github.com/fsprojects/Avalonia.FuncUI/issues/115)_

I tried to use LiveView with my https://github.com/JordanMarr/FSharp.ChordParser project, but I have not yet been able to get it to work.

# Steps

* Since I do not use Paket, I used `nuget` to install the analyzer to `packages/analyzers`:
```
nuget install SilkyFowl.Avalonia.FuncUI.LiveView.Analyzer -Version 0.0.1-alpha2 -OutputDirectory packages/analyzers
```

* I installed LiveView to my UI project:
```
<PackageReference Include="SilkyFowl.Avalonia.FuncUI.LiveView" Version="0.0.1-alpha2" />
```

* I debugged using the correct launch profile:

![image](https://user-images.githubusercontent.com/1030435/174497855-cd7b062f-5c20-46d0-85ee-bfb378670d5c.png)

* My `Program.fs` is setup the same as your readme.

* I added the `[<LivePreview>]` to my render function:
![image](https://user-images.githubusercontent.com/1030435/174497981-5638321a-8490-4814-a5d8-597f4d711561.png)

# Results

But the LivePreview window says "the FuncUiAnalyzer server is not active":

![image](https://user-images.githubusercontent.com/1030435/174497902-468ab0e2-c8ef-43b2-b409-a587df3b254e.png)

My changes here in the LivePreview branch:
https://github.com/JordanMarr/FSharp.ChordParser/tree/LivePreview

Commit: 
https://github.com/JordanMarr/FSharp.ChordParser/commit/48254bbdb7619630015c6d9dda586784d7117333

**Comment by SilkyFowl** [comment]
Thanks for the report.
I will try to check it out.

**Comment by SilkyFowl** [comment]
@JordanMarr I have not yet been able to reproduce this issue, but I have noticed an incompleteness in the documentation.
In addition to starting the FuncUIApp with LivePreview enabled, Analyzer must be started for LIvePrevie to start.
Specifically, after setting `FSharp.enableAnalyzers` to `true`, you need to focus or enter some text in a Project or Solution fsx file that `Ionide for F#` recognizes.
(Analyzer will not start with fsx files that are not included in a project, etc.)

> **Note**
> Nuget cli is unusable with error `1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`, so Analyzer is downloaded from the browser, unzipped directly.

https://user-images.githubusercontent.com/16532218/174569038-4c7b3e36-9f13-4535-91d4-9fd0b66865ee.mp4

When Analyzer is started, an error is displayed by setting `Grid.rowDefinitions` to an incorrect value, as shown below. Could you please confirm this?

![image](https://user-images.githubusercontent.com/16532218/174565053-9b1035e9-9df6-4a2a-a21a-7d9594ec57e1.png)


If Analyzer is running but LivePreview is not, then there may be a network problem.
The current implementation has a fixed network setting of localhost 8080, so if this port is already used by Docker, etc., it may not work correctly.
I would like to solve this by making it possible to change this in a configuration file, environment variable, etc., or by using a named pipe implementation.

**Comment by JordanMarr** [comment]
It still doesn't work for me. I do have Docker Desktop for Windows installed, so maybe that is affecting it?

The `rowDefinitions` should look like this:
![image](https://user-images.githubusercontent.com/1030435/174836140-19651f8a-d24e-47eb-82cd-5ae3b5d857fe.png)

I tried editing and saving my fsproj and sln files but the LivePreview window still does not update. 
I also tried adding a test.fsx file to the project, editing and saving it, and switching between the various sln files.

**Comment by SilkyFowl** [comment]
I found the cause of the issue.
An incorrect version of `FSharp.Analyzers.SDK` was incorrectly loaded due to a misconfiguration of the nuget package.
Do you see the following error output in VScode?

![image](https://user-images.githubusercontent.com/16532218/174953751-fb2b0ab8-14cd-4ef9-be18-d7124c858ffd.png)

I will release alpha3 with the proper configuration, but until then, could you please try the following steps to see if you can resolve this issue?

1. close VScode.
2. delete `FSharp.Analyzers.SDK.0.0.1` from `packages\analyzers`

Now when you start VScode, Analyzer will be started.

** If you want to install it anew, add the option ` -DependencyVersion Ignore`.

**Comment by JordanMarr** [comment]
It's working! 😀
